version = 0.1

[default]

[default.global.parameters]
stack_name = "guia-tur-bra"

[default.build.parameters]
cached = true
parallel = false

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_prefix = "guia-tur-bra"
image_repositories = []
s3_bucket="sam-app-guiaturbra-1972"
#resolve_s3 = true
region = "us-east-1"
resolve_s3 = true

[default.package.parameters]
#resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
