AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  guia-tur-bra
  Função que faz a raspagem dos dados da página das cidades

Globals:
  Function:
    Runtime: python3.10
    Handler: app.lambda_handler
    Timeout: 20
    MemorySize: 128
    Layers:
      - !Ref LibsLayer
      # - !Ref CustomLayer
    Environment:
      Variables:
        REGION_NAME: us-east-1
        SQS_QUEUE_URL: !GetAtt CidadesQueue.QueueUrl

Resources:
  LibsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${AWS::StackName}-LibsLayer
      Description: Layer comum para as funções Lambda
      ContentUri: src/layer/libs
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile

  # CustomLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: !Sub ${AWS::StackName}-CustomLayer
  #     Description: Layer comum para as funções Lambda
  #     ContentUri: src/layer/custom
  #     CompatibleRuntimes:
  #       - python3.10
  #     RetentionPolicy: Retain
  #   Metadata:
  #     BuildMethod: python3.10

  CidadesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-CidadesFunction
      CodeUri: src/lambda/cidades
      Policies:
        - Statement:
            Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt CidadesQueue.Arn
      Layers:
        - !Ref LibsLayer

  # CidadeFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: !Sub ${AWS::StackName}-CidadeFunction
  #     CodeUri: src/lambda/cidade
  #     Events:
  #       CidadesQueue:
  #         Type: SQS
  #         Properties:
  #           Queue: !GetAtt CidadesQueue.Arn
  #           BatchSize: 1
#   CidadesQueue:
#     Type: AWS::SQS::Queue
#     Properties:
#       QueueName: CidadesQueue

# Outputs:
#   CidadesQueueUrl:
#     Value: !Ref CidadesQueue
#     Export:
#       Name: CidadesQueueUrl
