AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  guia-tur-bra
  Funcao que faz a raspagem dos dados da pagina das cidades

Globals:
  Function:
    Environment:
      Variables:
        REGION_NAME: us-east-1

Resources:
  CidadesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CidadesFunction
      CodeUri: src
      Handler: cidades.lambda_handler
      Runtime: python3.10
      Timeout: 20
      MemorySize: 128
      Environment:
        Variables:
          SQS_QUEUE_URL: !GetAtt CidadesQueue.QueueUrl
      Policies:
        - Statement:
            Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt CidadesQueue.Arn
    Metadata:
      BuildMethod: python3.10
      BuildArchitecture: x86_64

  CidadeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CidadeFunction
      CodeUri: src
      Handler: cidade.lambda_handler
      Runtime: python3.10
      Timeout: 20
      MemorySize: 128
      Events:
        CidadesQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt CidadesQueue.Arn
            BatchSize: 1
    Metadata:
      BuildMethod: python3.10
      BuildArchitecture: x86_64

  CidadesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CidadesQueue

Outputs:
  CidadesQueueUrl:
    Value: !Ref CidadesQueue
    Export:
      Name: CidadesQueueUrl
