AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  guia-tur-bra
  Funcao que faz a raspagem dos dados da pagina das cidades

Globals:
  Function:
    Environment:
      Variables:
        REGION_NAME: us-east-1

Resources:
  CidadesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/cidades
      Handler: app.lambda_handler
      Runtime: python3.10
      Timeout: 20
      MemorySize: 128
      # Layers:
      #   - !Ref FetchLayer
      Environment:
        Variables:
          SQS_QUEUE_URL: !GetAtt CidadesQueue.QueueUrl

  # FetchLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: guia-tur-brasil-libs
  #     ContentUri: layers/
  #     CompatibleRuntimes:
  #       - python3.10
  #     RetentionPolicy: Delete
  #   Metadata:
  #     BuildMethod: python3.10

  CidadesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CidadesQueue

Outputs:
  CidadesQueueUrl:
    Value: !Ref CidadesQueue
    Export:
      Name: CidadesQueueUrl
