AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  guia-tur-bra
  Função que faz a raspagem dos dados da página das cidades

Globals:
  Function:
    Runtime: python3.10
    Handler: app.lambda_handler
    Timeout: 20
    MemorySize: 128
    Layers:
      - !Ref LibsLayer
      - !Ref CustomLayer
    Environment:
      Variables:
        REGION_NAME: us-east-1
        SQS_QUEUE_URL: !GetAtt CidadesQueue.QueueUrl

Resources:
  LibsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: LibsLayer
      Description: Layer comum para as funções Lambda
      ContentUri: layer/libs
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.10

  CustomLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: CustomLayer
      Description: Layer comum para as funções Lambda
      ContentUri: layer/custom
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.10

  CidadesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CidadesFunction
      CodeUri: lambda/cidades
      Policies:
        - Statement:
            Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt CidadesQueue.Arn

  CidadeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CidadeFunction
      CodeUri: lambda/cidade
      Events:
        CidadesQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt CidadesQueue.Arn
            BatchSize: 1
  CidadesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CidadesQueue

Outputs:
  CidadesQueueUrl:
    Value: !Ref CidadesQueue
    Export:
      Name: CidadesQueueUrl
